# Generated by Django 6.0.6 on 2026-07-15 11:42

import sites_conformes.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_conformes_core', '0079_alter_catalogindexpage_body_alter_contentpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsdsfrconfig',
            name='iframe_allow_origins',
            field=models.TextField(blank=True, default='', help_text="One domain per line, without scheme or path (e.g. 'example.com'). Pages can then be embedded in an iframe from these HTTPS origins. The CMS admin can never be embedded from another origin.", validators=[sites_conformes.core.validators.validate_iframe_allow_origins], verbose_name='Allowed iframe origins'),
        ),
    ]
